### ISSUE TITLE
Decide which and how many TAB ITEMS should be on the APP

### ISSUE THREAD

**Issue by fran-6co** [fran-6co/Ecolingo#1]
![Image](https://github.com/user-attachments/assets/162bbe65-66fd-4a52-87f4-3a336c0a6258)

**Comment by fran-6co** [comment]
- name of the screens

**Comment by tanvi-t** [comment]
![Image](https://github.com/user-attachments/assets/79dc6b4c-1a18-42d2-8572-34150997119f)

**Comment by tanvi-t** [comment]
![Image](https://github.com/user-attachments/assets/c3c60a22-9088-400f-9a0f-7200e5e5cc7e)

**Comment by fran-6co** [comment]
- _home tab_
  - different cards: **watch** (video + quiz), **play** (match figures), **experience** (sign up to an event, if you assist, you will be given a code that you will be able to redeem after the event, each month there is an event), **challenges** (small description, add to _MY CHALLENGES_ tab).
  - home cards topics: **PLASTIC WASTE, URBAN FARMING, SUSTAINABLE FASHION, RENEWABLE ENERGY, WILDLIFE CONSERVATION.**

**Comment by tanvi-t** [comment]
![Image](https://github.com/user-attachments/assets/5c7f9a28-0e13-45dc-930c-89ceb7dc2a7f)

**Comment by tanvi-t** [comment]
![Image](https://github.com/user-attachments/assets/b09c4c0d-412a-4b05-a610-c3b09c5b5d15)

**Comment by tanvi-t** [comment]
Hi team, my bad, I forgot to add the My Garden tab that is very important as well. It's the tracking of the microgreens they're growing, similar to the old app version I may have shown. Could we add that tab to the top?

**Comment by fran-6co** [comment]
sure no problem, we will talk about this tab on next meeting this week

**Comment by tanvi-t** [comment]
Yes perfect!
