### ISSUE TITLE
Create an ECOLINGO logo

### ISSUE THREAD

**Issue by fran-6co** [fran-6co/Ecolingo#5]

**Comment by tanvi-t** [comment]
![Image](https://github.com/user-attachments/assets/c65bf8fc-2cbd-4bfd-aaa6-af9288223129)

**Comment by tanvi-t** [comment]
I explored a few logo options but kept it simple with a word logo

**Comment by fran-6co** [comment]
![Image](https://github.com/user-attachments/assets/f1fb44a0-c7df-4a1a-9c9c-f28a88488582)

**Comment by fran-6co** [comment]
we need 1024x1024 pixel pictures. preferably one for light mode and one for dark mode.

**Comment by tanvi-t** [comment]
![Image](https://github.com/user-attachments/assets/27758e1b-972a-4a4a-88d2-a80331a8b899)
![Image](https://github.com/user-attachments/assets/f5c951ec-f28f-4b40-a7d3-23362a5a67e2)

**Comment by fran-6co** [comment]
perfect:

![Image](https://github.com/user-attachments/assets/9e6ce988-4744-4539-b654-b06323975f28)

**Comment by fran-6co** [comment]
Dark mode:

![Image](https://github.com/user-attachments/assets/4bdd27e2-93e9-4f92-8449-2f768defa1a2)
